import { ListingData } from '../types';

export const generateEbayHTML = (data: ListingData): string => {
  // Helper to render specs
  const specsHtml = data.specifications
    .map(s => `<li style="box-sizing: border-box;">${s}</li>`)
    .join('');

  // Helper to render package includes
  const packageHtml = data.packageIncludes
    .map(s => `<li>${s}</li>`)
    .join('');

  // Helper to render about item bullets
  const aboutHtml = data.aboutItems
    .map(item => {
        // Split on first colon for bolding if present
        const splitIndex = item.indexOf(':');
        if(splitIndex > -1) {
            const title = item.substring(0, splitIndex + 1);
            const content = item.substring(splitIndex + 1);
            return `<li class="a-spacing-mini" style="box-sizing: border-box; list-style: disc; overflow-wrap: break-word; margin: 0px;"><span class="a-list-item" style="box-sizing: border-box;"><strong>${title}</strong>${content}</span></li>`
        }
        return `<li class="a-spacing-mini" style="box-sizing: border-box; list-style: disc; overflow-wrap: break-word; margin: 0px;"><span class="a-list-item" style="box-sizing: border-box;">${item}</span></li>`;
    })
    .join('');

  // Helper for Main Images
  const mainImagesHtml = data.mainImages.map((img, index) => `
    <tr>
        <td align="center">
            <img src="${img.url}" alt="${img.alt || `${data.title} - Image ${index + 1}`}" style="max-width:100%; height:auto; display:block; margin-bottom: 10px;">
        </td>
    </tr>
  `).join('');

  // Helper for Comparison Table Headers (Images & Titles)
  const comparisonHeaderHtml = data.comparisonItems.map(item => `
    <td style="padding:20px 10px; vertical-align: top; width: 20%;">
        <a href="${item.link}" target="_blank" style="text-decoration:none;">
            <img src="${item.image}" alt="${item.imageAlt || item.title}" style="width:100%; max-width:180px; height:180px; object-fit:contain; border-radius:6px; border: 1px solid #eee;">
            <p style="margin:0 auto; padding: 10px 0; font-size:14px; color:#000000; text-align: center; line-height: 1.2; height: 50px; overflow: hidden;">${item.title}</p>
            <button style="background:#008bfd; border:none; padding:8px 12px; color:white; border-radius:6px; cursor:pointer; font-weight:bold; font-size:12px; width: 100%;">Click here</button>
        </a>
    </td>
  `).join('');

  // Comparison Rows
  const createRow = (label: string, key: keyof typeof data.comparisonItems[0]) => `
     <tr style="border-bottom: 1px solid #eee;">
        <td style="padding:10px; font-weight:bold; text-align: left; background:#f9f9f9;">${label}</td>
        ${data.comparisonItems.map(item => `<td style="padding:10px;">${item[key]}</td>`).join('')}
     </tr>
  `;

  const comparisonRows = `
    ${createRow('Price', 'price')}
    ${createRow('Material', 'material')}
    ${createRow('Light Source', 'lightSource')}
    ${createRow('Base', 'base')}
  `;

  return `
<!-- Generated by eBay Template Builder -->
<div style="font-family: 'Verdana', sans-serif; color: #333; max-width: 1000px; margin: 0 auto; padding: 0; margin-bottom: 0;">
    <h2 style="padding: 30px 0 20px; margin: 0 auto 20px; text-align: center; max-width: 90%;">
        <span style="display: inline-block; padding: 10px 20px; text-align: center; background-color: rgba(0, 0, 0, 0.05); border-radius: 4px;">
            <font color="#212529" face="Verdana" size="5">${data.title}</font>
        </span>
    </h2>

    <table width="100%" cellspacing="0" cellpadding="0" border="0" align="center">
        <tbody>
            ${mainImagesHtml}
        </tbody>
    </table>

    <h2 style="font-size:24px; font-weight:bold; margin-bottom:20px; text-align:center; padding-top: 40px;">
        Compare with similar items
    </h2>

    <!-- Comparison Table -->
    <div style="width:100%; margin:0 auto; padding-bottom: 20px; text-align:center; overflow-x:auto;">
        <table style="border-collapse:collapse; font-size:14px; text-align:center; width: 100%; min-width: 600px;">
            <tbody>
                <tr>
                    <td style="width: 10%;"></td> <!-- Empty corner -->
                    ${comparisonHeaderHtml}
                </tr>
                ${comparisonRows}
            </tbody>
        </table>
    </div>

    <div style="max-width: 90%; margin: 0 auto; padding-bottom: 0;">
        
        <!-- PRODUCT INFORMATION -->
        <details open style="margin-bottom:20px; padding:15px; border: 1px solid #dddddd; border-radius: 5px;">
            <summary style="font-size:18px; font-weight:bold; color:#222; cursor:pointer; padding-bottom:5px;">PRODUCT INFORMATION</summary>
            <p style="margin-top:20px;"><strong style="font-size:16px; color:#222;">DESCRIPTION</strong></p>
            <ul>
                <li>${data.description}</li>
            </ul>

            <p style="margin-top:10px;"><strong style="font-size:16px; color:#222;">SPECIFICATIONS:</strong></p>
            <ul style="list-style-type: disc; padding-left: 20px;">
                ${specsHtml}
            </ul>

            <p style="margin-top: 10px;"><strong><font size="4">Package included:</font></strong></p>
            <ul style="list-style-type: disc; padding-left: 20px;">
               ${packageHtml}
            </ul>
        </details>

        <!-- ABOUT THIS ITEM -->
        <details style="margin-bottom:20px; padding:15px; border: 1px solid #dddddd; border-radius: 5px;">
            <summary style="font-size:18px; font-weight:bold; color:#222; cursor:pointer; padding-bottom:5px;">ABOUT THIS ITEM</summary>
            <ul class="a-unordered-list a-vertical a-spacing-mini" style="margin: 10px 0 0 18px; color: #0f1111; padding: 0px;">
                ${aboutHtml}
            </ul>
        </details>

        <!-- TERMS & CONDITIONS -->
        <details style="margin-bottom:20px; padding:15px; border: 1px solid #dddddd; border-radius: 5px;">
            <summary style="font-size:18px; font-weight:bold; color:#222; cursor:pointer;">TERMS & CONDITIONS</summary>
            <h3 style="color:#222; margin-top:10px;">POSTAGE</h3>
            <ul style="list-style-type: disc; padding-left:20px; color:#555;">
                <li><font color="#555555">Order will be dispatched within 1 working day (Mon-Fri) via Royal Mail 48hrs / 2nd class. Delivery normally takes&nbsp;</font><strong><font color="#873d92">3-5 working days</font></strong><font color="#555555">&nbsp;for standard service.</font></li>
                <li>We will only send replacement items once Royal Mail confirms the item is lost.</li>
                <li>As Per eBay Guidelines, We Are Unable to Change Your Shipping Address Once We Received Your Payment.</li>
            </ul>

            <h3 style="color:#222; margin-top:10px;">RETURNS & REFUNDS</h3>
            <ul style="list-style-type: disc; padding-left:20px; color:#555;">
                <li><font color="#555555">We have a</font><strong><font color="#9e2048">&nbsp;60 days</font></strong><font color="#555555">&nbsp;no-quibble return policy.</font></li>
                <li>Buyer pays for the return postage.</li>
            </ul>
            
            <h3 style="font-family: Arial, sans-serif; margin-top: 20px;">CONTACT</h3>
            <ul style="font-family: Arial, sans-serif; color: rgb(51, 51, 51); line-height: 1.6; padding-left: 20px;">
                <li>If you have any questions or concerns, please send a message to the eBay messaging system; we will get back within 24hrs.</li>
                <li>Working Days: Monday - Friday</li>
                <li>Working Hours: 8:00 AM - 4:00 PM</li>
            </ul>
        </details>

        <!-- SHIPPING DETAILS -->
        <details style="margin-bottom:20px; padding:15px; border: 1px solid #dddddd; border-radius: 5px;">
            <summary style="font-size:18px; font-weight:bold; color:#222; cursor:pointer;">SHIPPING DETAILS</summary>
            <ul style="list-style-type: disc; padding-left:20px; color:#555;">
                <li><strong>FREE SHIPPING:</strong>&nbsp;${data.shippingInfo.freeShipping}</li>
                <li><strong>FIRST CLASS:</strong>&nbsp;${data.shippingInfo.firstClass}</li>
                <li><strong>INTERNATIONAL ORDERS:</strong>&nbsp;${data.shippingInfo.international}</li>
            </ul>
        </details>

        <!-- ABOUT US -->
        <details style="padding:15px; border: 1px solid #dddddd; border-radius: 5px; margin: 0;">
            <summary style="font-size:18px; font-weight:bold; color:#222; cursor:pointer;">ABOUT US</summary>
            <a href="${data.ebayStoreUrl}" target="_blank" style="text-decoration:none;">
                <img src="${data.logoUrl}" alt="${data.logoAlt || `${data.title} - eBay Store Logo`}" style="margin: 10px; padding-top: 20px; max-width:180px; object-fit:contain;">
            </a>
            <p style="color:#555; margin-top:10px;">${data.aboutUs}</p>
        </details>
    </div>
</div>
  `;
};
